#' Create a dataframe for manual targets for all layers, including the features and the constraints
#'
#' @description This function creates a dataframe with the comibination of feature targets, generated by `features_targets()` and the targets for constraints to be used in prioritizr
#'
#' @param feature_targets a dataframe of feature targets generated by `features_targets()`
#' @param patch_df a dataframe generated by `create_patch_df()` that includes constraints for each patch and grid cell combination
#'
#' @return A dataframe to be used to specify all manual targets for prioritizr
#' @export
#'
#' @examples
#' ## To be updated later
#' # Crate patches from layer
#' patches_raster <- create_patches(seamounts_raster)
#' # Create patch dataframe
#' patches_raster_df <- create_patch_df(planning_grid = planning_raster, features = features_raster, patches = patches_raster)
#' # Create target features - using just 20% for every feature
#' features_targets <- features_targets(targets = rep(0.2, (terra::nlyr(features_raster)) + 1), features = features_raster, pre_patches = seamounts_raster)
#' # Create constraint targets
#' constraint_targets <- constraints_targets(feature_targets = features_targets, patch_df = patches_raster_df)

constraints_targets <- function(feature_targets, patch_df) {

  constraints_number <- length(grep("constraint", names(patch_df)))

  feature_data_w_constraints <- tibble::tibble(id = seq(from = nrow(feature_targets)+1, to = (nrow(feature_targets) + constraints_number), by = 1), total = 2) %>%
    dplyr::mutate(name = sprintf("constraint_%d", id-nrow(feature_targets)), .after = id) %>%
    dplyr::mutate(relative_target = NA_real_,
                  absolute_target = 1) %>%
    dplyr::bind_rows(feature_targets, .)

  manual_targets <- tibble::tibble(feature = feature_data_w_constraints$name,
                           type = "absolute") %>%
    dplyr::mutate(sense = ifelse(grepl("constraint", feature) | feature == "locked_out",
                                 "<=", ">="),
                  target = c(dplyr::pull(feature_targets, absolute_target), rep(1, constraints_number)))

  return(manual_targets)
  }
