#' Create a dataframe for manual targets for all layers, including the features
#' and the constraints
#'
#' @description This function creates a dataframe with the combination of
#'   feature targets, generated by `features_targets()` and the targets for
#'   constraints to be used in prioritizr
#'
#' @param feature_targets a dataframe of feature targets generated by
#'   `features_targets()`
#' @param patch_df a dataframe generated by `create_patch_df()` that includes
#'   constraints for each patch and grid cell combination
#'
#' @return A dataframe to be used to specify all manual targets for prioritizr
#' @export
#'
#' @examples
#'# Import some planning data
#'
#'#import planning units/ cost raster
#'pu_raster <- terra::rast(system.file("extdata/pu_raster.tif", package = "patchwise"))

#'#import species distributions - feature data for planning
#'species_distributions <- terra::rast(system.file("extdata/spp_distributions.tif", package = "patchwise"))
#'
#'#import seamounts
#'seamounts <- terra::rast(system.file("extdata/seamounts.tif", package = "patchwise"))
#'
#'# Create seamount patches as multi-layer raster
#'patches_raster <- create_patches(seamounts)
#'
#'patches_df <- create_patch_df(spatial_grid = pu_raster, features = species_distributions,
#'patches = patches_raster, costs = pu_raster)
#'
#'# Create targets for protection - use 20% for each feature (including 20% of whole seamounts) in this example
#'targets_df <- features_targets(targets = rep(0.2, (terra::nlyr(species_distributions) + 1)), features = species_distributions, pre_patches = seamounts)
#'
#'# Add these targets to targets for protection for the "constraints" we introduced to protect entire seamount patches
#'constraints_df <- constraints_targets(feature_targets = targets_df, patch_df = patches_df)


constraints_targets <- function(feature_targets, patch_df) {

  # Add error for incorrect format of feature
  if(!check_df(feature_targets)) { stop("feature_targets must be a dataframe object")}
  if(!check_df(patch_df)) { stop("patch_df must be a dataframe object")}

  constraints_number <- length(grep("constraint", names(patch_df)))

  feature_data_w_constraints <- tibble::tibble(id = seq(from = nrow(feature_targets)+1, to = (nrow(feature_targets) + constraints_number), by = 1), total = 2) %>%
    dplyr::mutate(name = sprintf("constraint_%d", id-nrow(feature_targets)), .after = id) %>%
    dplyr::mutate(relative_target = NA_real_,
                  absolute_target = 1) %>%
    dplyr::bind_rows(feature_targets, .)

  manual_targets <- tibble::tibble(feature = feature_data_w_constraints$name,
                           type = "absolute") %>%
    dplyr::mutate(sense = ifelse(grepl("constraint", feature) | feature == "locked_out",
                                 "<=", ">="),
                  target = c(dplyr::pull(feature_targets, absolute_target), rep(1, constraints_number)))

  return(manual_targets)
  }
