#' Create boundary matrix for prioritizr if you are using patches
#'
#' @description This function creates a boundary matrix which is required if you
#'   want to use a boundary penalty in prioritizr
#'
#' @param spatial_grid a raster or sf template with the desired resolution and
#'   coordinate reference system; values in areas of interest are 1, while all
#'   other values are NA (only required if feature is a sf object)
#' @param patches a raster or sf object generated by `create_patches()`; a
#'   single feature split into spatially distinct groups; each layer of the
#'   raster or each column of the sf object identifies the location of each
#'   patch
#' @param patch_df a dataframe generated by `create_patch_df()` that includes
#'   constraints for each patch and grid cell combination
#'
#' @return A sparse matrix
#' @export
#'
#' @examples
#'# Import some planning data
#'
#'#import planning units/ cost raster
#'pu_raster <- terra::rast(system.file("extdata/pu_raster.tif", package = "patchwise"))

#'#import species distributions - feature data for planning
#'species_distributions <- terra::rast(system.file("extdata/spp_distributions.tif", package = "patchwise"))
#'
#'#import seamounts
#'seamounts <- terra::rast(system.file("extdata/seamounts.tif", package = "patchwise"))
#'
#'# Create seamount patches as multi-layer raster
#'patches_raster <- create_patches(seamounts)
#'
#'patches_df <- create_patch_df(spatial_grid = pu_raster, features = species_distributions,
#'patches = patches_raster, costs = pu_raster)
#'
#'#Create boundary matrix if you want to use a boundary penatly function in prioritizr
#'boundary_matrix <- create_boundary_matrix(spatial_grid = pu_raster, patches = patches_raster, patch_df = patches_df)


create_boundary_matrix <- function(spatial_grid, patches, patch_df){

  # Add error for incorrect format of feature
  if(!check_raster(spatial_grid) & !check_sf(spatial_grid)) { stop("spatial_grid must be a raster or sf object")}
  if(!check_raster(patches) & !check_sf(patches)) { stop("patches must be a raster or sf object")}
  if(!check_df(patch_df)) { stop("patch_df must be a dataframe object")}
  if(!check_matching_crs(spatial_grid, patches)) { stop("spatial_grid and patches must be of the same crs")}
  if(!check_matching_type(spatial_grid, patches)) { stop("spatial_grid and patches must be of the same object type (all raster or all sf)")}

  if(class(spatial_grid)[1] %in% c("RasterLayer", "SpatRaster")){
    patch_ids <- patch_df %>%
      dplyr::slice_tail(n = terra::nlyr(patches)) %>%
      dplyr::pull(1)

    spatial_grid_sf <- terra::as.polygons(spatial_grid, aggregate = FALSE, na.rm = FALSE) %>%
      sf::st_as_sf()

  } else {
    patch_ids <- patch_df %>%
      dplyr::slice_tail(n = ncol(patches %>% sf::st_drop_geometry())) %>%
      dplyr::pull(1)

    spatial_grid_sf <- spatial_grid
  }

  planning_unit_sf <-
    spatial_grid_sf %>%
    sf::st_drop_geometry() %>%
    dplyr::mutate(geometry = sf::st_geometry(spatial_grid_sf)) %>%
    sf::st_set_geometry(., "geometry") %>%
    dplyr::select(geometry) %>%
    dplyr::bind_rows(
      lapply(patch_ids, function(i) {
        sf::st_sf(layer = 1, geometry = sf::st_union(spatial_grid_sf[i, , drop = FALSE]))
      }) %>%
        do.call(what = dplyr::bind_rows) %>%
        dplyr::select(-layer)
    )

  return(prioritizr::boundary_matrix(planning_unit_sf))
}
