#' Create boundary matrix for prioritizr if you are using patches
#'
#' @description This function creates a boundary matrix to plug into prioritizr
#'
#' @param planning_grid a raster or sf template with the desired resolution and coordinate reference system generated by `offshoredatr::get_planning_grid()`; values in areas of interest are 1, while all other values are NA (only required if feature is a sf object)
#' @param patches a raster or sf object generated by `create_patches()`; a single feature split into spatially distinct groups; each layer of the raster or each column of the sf object identifies the location of each patch
#' @param patch_df a dataframe generated by `create_patch_df()` that includes constraints for each patch and grid cell combination
#'
#' @return A boundary matrix to plug into prioritizr
#' @export
#'
#' @examples
#' ## To be updated later
#' # Create patches from seamount raster data
#' seamount_patches <- create_patches(seamount_raster)
#' # Create dataframe from patches
#' patches_raster_df <- create_patch_df(planning_grid = planning_raster, features = features_raster, patches = seamount_patches)
#' # Run boundary matrix
#' boundary_matrix <- create_boundary_matrix(planning_grid = planning_raster, patches = seamount_patches, patch_df = patches_raster_df)

create_boundary_matrix <- function(planning_grid, patches, patch_df){

  if(class(planning_grid)[1] %in% c("RasterLayer", "SpatRaster")){
    patch_ids <- patch_df %>%
      dplyr::slice_tail(n = terra::nlyr(patches)) %>%
      dplyr::pull(1)

    planning_grid_sf <- terra::as.polygons(planning_grid, aggregate = FALSE, na.rm = FALSE) %>%
      sf::st_as_sf()

  } else {
    patch_ids <- patch_df %>%
      dplyr::slice_tail(n = ncol(patches %>% sf::st_drop_geometry())) %>%
      dplyr::pull(1)

    planning_grid_sf <- planning_grid
  }

  planning_unit_sf <-
    planning_grid_sf %>%
    sf::st_drop_geometry() %>%
    dplyr::mutate(geometry = sf::st_geometry(planning_grid_sf)) %>%
    sf::st_set_geometry(., "geometry") %>%
    dplyr::select(geometry) %>%
    dplyr::bind_rows(
      lapply(patch_ids, function(i) {
        sf::st_sf(layer = 1, geometry = sf::st_union(planning_grid_sf[i, , drop = FALSE]))
      }) %>%
        do.call(what = dplyr::bind_rows) %>%
        dplyr::select(-layer)
    )

  return(prioritizr::boundary_matrix(planning_unit_sf))
}
